### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by nekkitl** [MaxSecurity/BurpSuite-MacOS-Crack#2]
To download needs Baidu account, that can't be registered w/o china phone number...
Please, upload to other places.

**Comment by MaxSecurity** [comment]
The NaiNiu download link has been updated and can be downloaded directly

**Comment by MaxSecurity** [comment]
> To download needs Baidu account, that can't be registered w/o china phone number... Please, upload to other places.

The NaiNiu download link has been updated and can be downloaded directly
